//
//  LeftPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/11/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LeftPresenterInput {
    func presentSomething(response: Left.Something.Response)
}

protocol LeftPresenterOutput: class {
    func displaySomething(viewModel: Left.Something.ViewModel)
}

class LeftPresenter: LeftPresenterInput {
    weak var output: LeftPresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: Left.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = Left.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
