//
//  LeftViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/11/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LeftViewControllerOutput {
    func fetchUser()
}

class LeftViewController: UIViewController {
    var output: LeftViewControllerOutput!
    var router: LeftRouter!
    
    var invoices: UINavigationController!
    var settings: UINavigationController!

    @IBOutlet weak var name: UILabel!
    @IBOutlet weak var email: UILabel!
    @IBOutlet weak var entity: UILabel!
    @IBOutlet weak var tableView: UITableView!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        LeftConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        LeftConfigurator.sharedInstance.dataSourceConfigure(viewController: self)
        setupControllers()
        setupTableView()
        fetchUser()
    }

    // MARK: - Event handling

    func setupControllers() {
        self.invoices = UIStoryboard(name: "InvoicesAndReceipts", bundle: Bundle.main).instantiateInitialViewController() as! UINavigationController
        self.settings = UIStoryboard(name: "Settings", bundle: Bundle.main).instantiateInitialViewController() as! UINavigationController
    }
    
    func setupTableView() {
        tableView.register(LeftCell.nib, forCellReuseIdentifier: LeftCell.cellId)
    }
    
    func fetchUser() {
        output.fetchUser()
    }
    
    // MARK: - Display logic

    func displayUserInfo(viewModel: Left.User.ViewModel) {
        name.text = viewModel.name
        email.text = viewModel.email
        entity.text = viewModel.entityName
    }
}

extension LeftViewController: LeftDataSourceOutput {
    func didSelect(type: LeftDataSourceType) {
        switch type {
        case .invoice: slideMenuController()?.changeMainViewController(invoices, close: true)
        case .settings: slideMenuController()?.changeMainViewController(settings, close: true)
        case .logout: showLogoutAlert()
        }
    }
    
    func showLogoutAlert() {
        let alert = UIAlertController(title: "Sign Out", message: "Are You Sure?", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
        alert.addAction(UIAlertAction(title: "Yes", style: .default, handler: { [weak self] _ in self?.logout() }))
        
        navigationController?.present(alert, animated: true, completion: nil)
    }
    
    func logout() {
        AppSettings.shared.logout()
        DispatchQueue.main.async {
            AppConfigurator.shared.show(for: .auth)
        }
    }
}
