//
//  LeftPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/11/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LeftPresenterOutput: class {
    func displayUserInfo(viewModel: Left.User.ViewModel)
}

class LeftPresenter {
    weak var output: LeftPresenterOutput!

    // MARK: - Presentation logic
    func presentUserInfo(response: Left.User.Response) {
        let user = response.userInfo
        let viewModel = Left.User.ViewModel(name: user.fullName ?? "",
                                            email: user.emailAddress ?? "",
                                            entityName: user.orgName ?? "")
        
        output.displayUserInfo(viewModel: viewModel)
    }
}
