//
//  LeftConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/11/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension LeftViewController: LeftPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension LeftInteractor: LeftViewControllerOutput {
}

extension LeftPresenter: LeftInteractorOutput {
}

class LeftConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = LeftConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: LeftViewController) {
        let router = LeftRouter()
        router.viewController = viewController

        let presenter = LeftPresenter()
        presenter.output = viewController

        let interactor = LeftInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
