//
//  LeftModels.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/11/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Left {
    struct User {
        struct Response {
            let userInfo: AuthResponse
        }
        
        struct ViewModel {
            let name: String
            let email: String
            let entityName: String
        }
    }
}
