//
//  LeftInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/11/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LeftInteractorInput {
    func doSomething(request: Left.Something.Request)
}

protocol LeftInteractorOutput {
      func presentSomething(response: Left.Something.Response)
}

class LeftInteractor: LeftInteractorInput {
    var output: LeftInteractorOutput!
    var worker: LeftWorker!

    // MARK: - Business logic

    func doSomething(request: Left.Something.Request) {
        // NOTE: Create some Worker to do the work

        worker = LeftWorker()
        worker.doSomeWork()

        // NOTE: Pass the result to the Presenter

        let response = Left.Something.Response()
        output.presentSomething(response: response)
    }
}
