//
//  SignUpViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Material

protocol SignUpViewControllerOutput {
    var email: String! { get set }
    func tryToSignUp(request: SignUp.Register.Request)
}

class SignUpViewController: EmailPasswordViewController {
    var output: SignUpViewControllerOutput!
    var router: SignUpRouter!

    @IBAction func register(_ sender: Button) {
        tryToSignUp()
    }
    
    @IBAction func forgetPassword(_ sender: UIButton) {
    }
    
    @IBAction func goBack(_ sender: UIButton) {
        navigationController?.popViewController(animated: true)
    }
    
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        SignUpConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - Event handling

    func tryToSignUp() {
        startSpinning()
        let request = SignUp.Register.Request(email: textFields[0].text,
                                              password: textFields[1].text)
        output.tryToSignUp(request: request)
    }

    // MARK: - Display logic

    func displayRegister(viewModel: SignUp.Register.ViewModel) {
        output.email = viewModel.email
        router.navigateToCompleteProfile()
    }
}
