//
//  SignUpPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignUpPresenterOutput: class, Errorable, Spinnable {
    func displayRegister(viewModel: SignUp.Register.ViewModel)
}

class SignUpPresenter {
    weak var output: (SignUpPresenterOutput & PasswordRecoveryPresenterOutput)!

    // MARK: - Presentation logic
    func presentRegister(response: SignUp.Register.Response) {
        output.stopSpinning()
        
        switch response.data {
        case .none(let message): output.show(type: .error(message: message))
        case .value(let data):
            guard data.message.isEmpty else { output.show(type: .error(message: data.message)); return }
            guard !data.userAlreadyCreated else { output.show(type: .error(message: "User Already Registered, Please Verify your Email Address")); return }
            guard !data.isVerified else { output.show(type: .error(message: "User Already Registered, Please Login From Your Email Address")); return }
            
            let viewModel = SignUp.Register.ViewModel(email: data.email)
            output.displayRegister(viewModel: viewModel)
        }
    }
    
    func presentRecoveredPassword(response: PasswordRecoveryModel.Response) {
        output.stopSpinning()
        
        switch response.status {
        case .none(let message): output.show(type: .error(message: message))
        case .value(let status):
            if status.status || status.isEmailVerified { output.show(type: .success(message: status.details)) }
            else { output.show(type: .error(message: status.details)) }
        }
    }
}
