//
//  SignUpModels.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct SignUp {
    struct Register {
        struct Request {
            let email: String?
            let password: String?
        }
        
        struct Response {
            let data: RebotValueWrapper<SignUpFirstResponse>
        }
        
        struct ViewModel {
            let email: String
        }
    }
}
