//
//  SignInWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SignInWorker: EmailPasswordWorker {
    func tryToLogin(callback: @escaping (RebotValueWrapper<AuthResponse>) -> ()) {
        AuthResponse.loadType(request: API.signIn(params)) { (auth, message) in
            guard message == nil else { callback(.none(message: message!)); return }
            
            /// Save the response into database
            let user: UserInfo = DatabaseManager.shared.insert(response: auth!)
            
            /// Save the user info into singleton
            AppSettings.shared.store(user: user)
            
            callback(.value(auth!))
        }
    }
}
