//
//  SignInViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Material
import MBProgressHUD
import RxSwift
import RxCocoa

protocol SignInViewControllerOutput {
    func tryToLogin(request: SignIn.Login.Request)
}

class SignInViewController: EmailPasswordViewController {
    fileprivate var spinner: MBProgressHUD?
    var output: SignInViewControllerOutput!
    var router: SignInRouter!
    
    @IBAction func login(_ sender: Button) {
        tryToLogin()
    }
    
    @IBAction func forgotPassword(_ sender: UIButton) {
    }
    
    @IBAction func openSignUp(_ sender: UIButton) {
        router.navigateToSignUp()
    }
    
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        SignInConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - Event handling

    func tryToLogin() {
        let request = SignIn.Login.Request(email: textFields?[0].text,
                                           password: textFields?[1].text)
        output.tryToLogin(request: request)
        
        startSpinning()
    }

    // MARK: - Display logic
    
    func displayMain() {
        router.displayMain()
    }
}
