//
//  SignInRouter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignInRouterInput {
    func navigateToSignUp()
    func navigateToCompleteProfile()
    func displayMain()
}

class SignInRouter: SignInRouterInput {
    weak var viewController: SignInViewController!

    // MARK: - Navigation

    func navigateToSignUp() {
         viewController.performSegue(withIdentifier: "ShowSignUp", sender: nil)
    }
    
    func navigateToCompleteProfile() {
        viewController.performSegue(withIdentifier: "ShowProfileCompletion", sender: nil)
    }
    
    func displayMain() {
        AppConfigurator.shared.show(for: .main)
    }
    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == "ShowProfileCompletion" {
            passDataToProfileCompletion(segue: segue)
        }
    }
    
    func passDataToProfileCompletion(segue: UIStoryboardSegue) {
        let completionProfile = segue.destination as! CompleteProfileViewController
        completionProfile.output.externalInfo = viewController.output.completeProfileInfo
        completionProfile.output.type = viewController.output.completeProfileInfo.type
        completionProfile.output.email = viewController.output.completeProfileInfo.email
    }
}
