//
//  SignInRouter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignInRouterInput {
    func navigateToSignUp()
    func displayMain()
}

class SignInRouter: SignInRouterInput {
    weak var viewController: SignInViewController!

    // MARK: - Navigation

    func navigateToSignUp() {
         viewController.performSegue(withIdentifier: "ShowSignUp", sender: nil)
    }
    
    func displayMain() {
        AppConfigurator.shared.show(for: .main)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }

    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene

        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
