//
//  CompleteProfilePresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CompleteProfilePresenterInput {
    func presentSomething(response: CompleteProfile.Something.Response)
}

protocol CompleteProfilePresenterOutput: class {
    func displaySomething(viewModel: CompleteProfile.Something.ViewModel)
}

class CompleteProfilePresenter: CompleteProfilePresenterInput {
    weak var output: CompleteProfilePresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: CompleteProfile.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = CompleteProfile.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
