//
//  CompleteProfileInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CompleteProfileInteractorInput {
    func doSomething(request: CompleteProfile.Something.Request)
}

protocol CompleteProfileInteractorOutput {
      func presentSomething(response: CompleteProfile.Something.Response)
}

class CompleteProfileInteractor: CompleteProfileInteractorInput {
    var output: CompleteProfileInteractorOutput!
    var worker: CompleteProfileWorker!
    
    var email: String!

    // MARK: - Business logic

    func doSomething(request: CompleteProfile.Something.Request) {
        // NOTE: Create some Worker to do the work

        worker = CompleteProfileWorker()
        worker.doSomeWork()

        // NOTE: Pass the result to the Presenter

        let response = CompleteProfile.Something.Response()
        output.presentSomething(response: response)
    }
}
