//
//  CompleteProfileConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/8/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension CompleteProfileViewController: CompleteProfilePresenterOutput {
}

extension CompleteProfileInteractor: CompleteProfileViewControllerOutput {
}

extension CompleteProfilePresenter: CompleteProfileInteractorOutput {
}

class CompleteProfileConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = CompleteProfileConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: CompleteProfileViewController) {
        let router = CompleteProfileRouter()
        router.viewController = viewController

        let presenter = CompleteProfilePresenter()
        presenter.output = viewController

        let interactor = CompleteProfileInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
