//
//  DetailInvoiceRouter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailInvoiceRouterInput {
    func navigateToZoomWeb()
    func navigateToZoomImage()
}

class DetailInvoiceRouter: DetailInvoiceRouterInput {
    weak var viewController: DetailInvoiceViewController!

    // MARK: - Navigation

    func navigateToZoomWeb() {
        viewController.performSegue(withIdentifier: "showZoomWebView", sender: nil)
    }
    
    func navigateToZoomImage() {
        viewController.performSegue(withIdentifier: "showZoomScrollView", sender: nil)
    }
    
    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == "showZoomWebView" {
            passDataToWebScene(segue: segue)
        }
        else if segue.identifier == "showZoomScrollView" {
            passDataToScrollScene(segue: segue)
        }
    }

    func passDataToWebScene(segue: UIStoryboardSegue) {
        let vc = segue.destination as! ZoomWebViewController
        vc.url = viewController.output.originalInvoice?.fullMediaUrl
    }
    
    func passDataToScrollScene(segue: UIStoryboardSegue) {
        let vc = segue.destination as! ZoomScrollViewController
        vc.url = viewController.output.originalInvoice?.fullMediaUrl
    }
}
