//
//  DetailInvoicePresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailInvoicePresenterInput {
    func presentSomething(response: DetailInvoice.Something.Response)
}

protocol DetailInvoicePresenterOutput: class {
    func displaySomething(viewModel: DetailInvoice.Something.ViewModel)
}

class DetailInvoicePresenter: DetailInvoicePresenterInput {
    weak var output: DetailInvoicePresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: DetailInvoice.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = DetailInvoice.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
