//
//  DetailInvoiceViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Material

protocol DetailInvoiceViewControllerOutput {
    func save(request: DetailInvoice.Something.Request)
}

class DetailInvoiceViewController: UITableViewController {
    var output: DetailInvoiceViewControllerOutput!
    var router: DetailInvoiceRouter!
    
    @IBOutlet weak var invoicePhoto: UIImageView!
    @IBOutlet var textFields: [TextField]!
    
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        DetailInvoiceConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work

        let request = DetailInvoice.Something.Request()
        output.save(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel: DetailInvoice.Something.ViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
