//
//  DetailInvoiceConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension DetailInvoiceViewController: DetailInvoicePresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension DetailInvoiceInteractor: DetailInvoiceViewControllerOutput {
}

extension DetailInvoicePresenter: DetailInvoiceInteractorOutput {
}

class DetailInvoiceConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = DetailInvoiceConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: DetailInvoiceViewController) {
        let router = DetailInvoiceRouter()
        router.viewController = viewController

        let presenter = DetailInvoicePresenter()
        presenter.output = viewController

        let interactor = DetailInvoiceInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
