//
//  DetailInvoiceInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailInvoiceInteractorOutput {
    func presentInitialSetup(response: DetailInvoice.Setup.Response)
}

class DetailInvoiceInteractor {
    var output: DetailInvoiceInteractorOutput!
    var worker: DetailInvoiceWorker!
    
    var originalInvoice: SyncConvertedInvoiceResponse?

    // MARK: - Business logic
    func initialSetup() {
        let response = DetailInvoice.Setup.Response(with: originalInvoice)
        output.presentInitialSetup(response: response)
    }
    
    func save(request: DetailInvoice.Save.Request) {
        
    }
}
