//
//  DetailInvoiceWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class DetailInvoiceSaveWorker {
    let params: [String: Any]
    
    init(params: [String: Any]) {
        self.params = params
    }
    
    func save(callback: @escaping (RebotValueWrapper<SyncConvertedInvoiceResponse>) -> ()) {
        SyncConvertedInvoiceResponse.loadType(request: API.updateConvertedInvoice(with: params)) { (resp, message) in
            guard message == nil else { callback(.none(message: message!)); return }
            
            callback(.value(resp!))
        }
    }
}

class DetailInvoiceRejectWorker {
    let request: DetailInvoice.Reject.Params
    
    init(request: DetailInvoice.Reject.Params) {
        self.request = request
    }
    
    func reject(callback: @escaping (RebotValueWrapper<SyncConvertedInvoiceResponse>) -> ()) {
        SyncConvertedInvoiceResponse.loadType(request: API.reject(with: request.entityId,
                                                                  and: request.invoiceId,
                                                                  originalInvoiceId: request.originalInvoiceId,
                                                                  reason: request.comment)) { (resp, message) in
                                                                    guard message == nil else { callback(.none(message: message!)); return }
                                                                    
                                                                    callback(.value(resp!))
        }
    }
}
