//
//  DetailInvoiceViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ActionSheetPicker_3_0
import Material

protocol DetailInvoiceViewControllerOutput {
    var originalInvoice: SyncConvertedInvoiceResponse? { get set }
    
    func initialSetup()
    func save(request: DetailInvoice.Save.Request)
}

class DetailInvoiceViewController: UITableViewController {
    var output: DetailInvoiceViewControllerOutput!
    var router: DetailInvoiceRouter!
    
    @IBOutlet weak var webView: UIWebView!
    @IBOutlet var textFields: [TextField]!
    
    // MARK: - Object lifecycle
    override func awakeFromNib() {
        super.awakeFromNib()
        DetailInvoiceConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        initialSetup()
        
    }

    // MARK: - Event handling
    func initialSetup() {
        output.initialSetup()
    }
    
    func save() {
//        let request = DetailInvoice.Save.Request()
//        output.save(request: request)
    }

    // MARK: - Display logic
    func displayInitial(viewModel: DetailInvoice.Setup.ViewModel) {
        webView.loadRequest(viewModel.imageRequest)
        textFields?[0].text = viewModel.supplierName
        textFields?[1].text = viewModel.invoiceDate
        textFields?[2].text = viewModel.invoiceNumber
        textFields?[3].text = viewModel.paymentMethod
        textFields?[4].text = viewModel.category
        textFields?[5].text = viewModel.taxRate
        textFields?[6].text = viewModel.taxAmount
        textFields?[7].text = viewModel.grossAmount
        textFields?[8].text = viewModel.netAmount
        textFields?[9].text = viewModel.dueDate
    }
}
