//
//  SlideMenuViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 3/28/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

import SlideMenuControllerSwift

class SlideMenuViewController: SlideMenuController {
    override func viewDidLoad() {
        super.viewDidLoad()
        SlideMenuConfigurator.sharedInstance.configure(viewController: self)
    }
}
