//
//  SettingsModels.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 5/30/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Settings {
    struct Camera {
        struct Response {
            let crop: Bool
        }
        
        struct ViewModel {
            let state: Bool
        }
    }
}
