//
//  SettingsInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 5/30/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingsInteractorInput {
    func loadInitialSettings()
    func saveEnableCrop(with state: Bool)
}

protocol SettingsInteractorOutput {
    func presentInitialSettings(response: Settings.Camera.Response)
}

class SettingsInteractor: SettingsInteractorInput {
    var output: SettingsInteractorOutput!
    let ud = UserDefaults.standard

    // MARK: - Business logic

    func loadInitialSettings() {
        let crop = ud.bool(forKey: "SettingsCropEnabled")
        let response = Settings.Camera.Response(crop: crop)
        output.presentInitialSettings(response: response)
    }
    
    func saveEnableCrop(with state: Bool) {
        ud.set(state, forKey: "SettingsCropEnabled")
    }
}
