//
//  SettingsViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 5/30/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Material

protocol SettingsViewControllerInput {
    func displayCameraSettings(viewModel: Settings.Camera.ViewModel)
}

protocol SettingsViewControllerOutput {
    func loadInitialSettings()
    func saveEnableCrop(with state: Bool)
}

class SettingsViewController: UITableViewController, SettingsViewControllerInput {
    var output: SettingsViewControllerOutput!
    
    @IBOutlet weak var crop: UISwitch!

    @IBAction func cropChange(_ sender: UISwitch) {
        output.saveEnableCrop(with: sender.isOn)
    }
    
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        SettingsConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let menu = UIBarButtonItem(image: Icon.cm.menu, style: .plain, target: self, action: #selector(toggleLeft))
        navigationItem.leftBarButtonItem = menu
        
        loadInitialSettings()
    }

    // MARK: - Event handling

    func loadInitialSettings() {
        output.loadInitialSettings()
    }

    // MARK: - Display logic

    func displayCameraSettings(viewModel: Settings.Camera.ViewModel) {
        crop.isOn = viewModel.state
    }
    
    // MARK: - UITableViewDelegate
    override func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return 0.01
    }
}
