//
//  SettingsConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 5/30/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension SettingsViewController: SettingsPresenterOutput {
}

extension SettingsInteractor: SettingsViewControllerOutput {
}

extension SettingsPresenter: SettingsInteractorOutput {
}

class SettingsConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = SettingsConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: SettingsViewController) {
        let presenter = SettingsPresenter()
        presenter.output = viewController

        let interactor = SettingsInteractor()
        interactor.output = presenter

        viewController.output = interactor
    }
}
