//
//  SettingsPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 5/30/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingsPresenterInput {
    func presentInitialSettings(response: Settings.Camera.Response)
}

protocol SettingsPresenterOutput: class {
    func displayCameraSettings(viewModel: Settings.Camera.ViewModel)
}

class SettingsPresenter: SettingsPresenterInput {
    weak var output: SettingsPresenterOutput!

    // MARK: - Presentation logic

    func presentInitialSettings(response: Settings.Camera.Response) {
        let viewModel = Settings.Camera.ViewModel(state: response.crop)
        output.displayCameraSettings(viewModel: viewModel)
    }
}
