//
//  CameraRouter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CameraRouterInput {
    func navigateToPhotoVerify()
}

class CameraRouter: CameraRouterInput {
    weak var viewController: CameraViewController!

    // MARK: - Navigation

    func navigateToPhotoVerify() {
         viewController.performSegue(withIdentifier: "ShowPhotoVerifyScene", sender: nil)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "ShowPhotoVerifyScene" {
            passDataToCameraVerifyScene(segue: segue)
        }
    }

    func passDataToCameraVerifyScene(segue: UIStoryboardSegue) {
         let photoVerifyViewController = segue.destination as! PhotoVerifyViewController
         photoVerifyViewController.takenPhoto = viewController.takenPhoto
    }
}
