//
//  CameraConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension CameraViewController {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

class CameraConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = CameraConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: CameraViewController) {
        let router = CameraRouter()
        router.viewController = viewController

        viewController.router = router
    }
}
