//
//  PhotoVerifyPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PhotoVerifyPresenterOutput: class {
    func displaySomething()
}

class PhotoVerifyPresenter {
    weak var output: PhotoVerifyPresenterOutput!

    // MARK: - Presentation logic
    func presentSomething(response: PhotoVerify.Upload.Response) {
        output.displaySomething()
    }
}
