//
//  PhotoVerifyPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PhotoVerifyPresenterInput {
    func presentSomething(response: PhotoVerify.Something.Response)
}

protocol PhotoVerifyPresenterOutput: class {
    func displaySomething(viewModel: PhotoVerify.Something.ViewModel)
}

class PhotoVerifyPresenter: PhotoVerifyPresenterInput {
    weak var output: PhotoVerifyPresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: PhotoVerify.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = PhotoVerify.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
