//
//  PhotoVerifyWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class PhotoVerifyWorker {
    let params: PhotoVerify.Upload.Params
    
    init(params: PhotoVerify.Upload.Params) {
        self.params = params
    }
    
    func uploadFile(callback: @escaping (RebotValueWrapper<FileUploadResponse>) -> ()) {
        FileUploadResponse.loadType(request: API.fileUpload(with: params.params)) { (resp, message) in
            guard message == nil else { callback(.none(message: message!)); return }
            
            callback(.value(resp!))
        }
    }
}
