//
//  PhotoVerifyConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PhotoVerifyViewController: PhotoVerifyPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension PhotoVerifyInteractor: PhotoVerifyViewControllerOutput {
}

extension PhotoVerifyPresenter: PhotoVerifyInteractorOutput {
}

class PhotoVerifyConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = PhotoVerifyConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: PhotoVerifyViewController) {
        let router = PhotoVerifyRouter()
        router.viewController = viewController

        let presenter = PhotoVerifyPresenter()
        presenter.output = viewController

        let interactor = PhotoVerifyInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
