//
//  PhotoVerifyPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/13/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PhotoVerifyPresenterOutput: class, Errorable, Spinnable {
    func displayFile()
}

class PhotoVerifyPresenter {
    weak var output: PhotoVerifyPresenterOutput!

    // MARK: - Presentation logic
    func presentFile(response: PhotoVerify.Upload.Response) {
        DispatchQueue.main.async { [weak self] in
            self?.output.stopSpinning()
            
            switch response.data {
            case .none(let message): self?.output.show(type: .error(message: message))
            case .value: self?.output.displayFile()
            }
        }
    }
}
