//
//  DashboardWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Charts

class DashboardWorker {
    func fetchPieData(callback: (RebotValueWrapper<PieChartDataSet>) -> ()) {
        /// TODO: fetch from network
        
        /// TODO: Remove later, this needs to be build dynamically
        let values = [
            PieChartDataEntry(value: 100.0 / 2.90, label: "pending"),
            PieChartDataEntry(value: 40.0 / 2.90, label: "processed"),
            PieChartDataEntry(value: 40.0 / 2.90, label: "exported"),
            PieChartDataEntry(value: 30.0 / 2.90, label: "reject"),
            PieChartDataEntry(value: 80.0 / 2.90, label: "process")
        ]
        
        let dataSet = PieChartDataSet(values: values, label: nil)
        dataSet.drawIconsEnabled = false
        dataSet.sliceSpace = 0.0
        dataSet.iconsOffset = CGPoint(x: 0, y: 40)
        
        dataSet.colors = RebotColor.Pie.pieColors
        
        callback(.value(dataSet))
    }
}
