//
//  DashboardInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Charts

protocol DashboardInteractorOutput {
      func presentPieData(response: Dashboard.PieChart.Response)
}

class DashboardInteractor {
    var output: DashboardInteractorOutput!
    var worker: DashboardWorker!

    // MARK: - Business logic
    
    func fetchPieChart() {
        worker = DashboardWorker()
        worker.fetchPieData { [weak self] dataSet in
            DispatchQueue.main.async { self?.sendPieData(request: dataSet) }
        }
    }
    
    private func sendPieData(request dataSet: RebotValueWrapper<PieChartDataSet>) {
        let response = Dashboard.PieChart.Response(dataSet: dataSet)
        output.presentPieData(response: response)
    }
}
