//
//  ExpensesInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Charts

protocol ExpensesInteractorOutput {
      func presentLineChart(response: Expenses.Line.Response)
}

class ExpensesInteractor {
    var output: ExpensesInteractorOutput!
    var worker: ExpensesWorker!

    // MARK: - Business logic
    func fetchLineData() {
        worker = ExpensesWorker()
        worker.fetchLineData { [weak self] (set) in
            self?.pass(dataSet: set)
        }
    }
    
    func pass(dataSet: RebotValueWrapper<LineChartDataSet>) {
        let response = Expenses.Line.Response(dataSet: dataSet)
        output.presentLineChart(response: response)
    }
}
