//
//  ExpensesWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Charts

class ExpensesWorker {
    // MARK: - Business Logic
  
    func fetchLineData(callback: (RebotValueWrapper<LineChartDataSet>) -> ()) {
        /// TODO: fetch real data later
        let now = Date().timeIntervalSince1970
        let month = 60 * 60 * 24 * 31
        
        let values = [
            ChartDataEntry(x: now - Double((month * 6)), y: 0.0),
            ChartDataEntry(x: now - Double((month * 5)), y: 100_000_000.0),
            ChartDataEntry(x: now - Double((month * 4)), y: 400_000_000.0),
            ChartDataEntry(x: now - Double((month * 3)), y: 200_000_000.0),
            ChartDataEntry(x: now - Double((month * 2)), y: 1_000_000_000.0),
            ChartDataEntry(x: now - Double(month), y: 145_223_223.0)
        ]
        
        let dataSet = LineChartDataSet(values: values, label: nil)
        dataSet.colors = [.green]
        dataSet.drawValuesEnabled = true
        dataSet.drawCirclesEnabled = true
        dataSet.circleColors = [.blue]
        dataSet.drawCircleHoleEnabled = true
        dataSet.circleHoleColor = .white
        dataSet.lineWidth = 3.0
        dataSet.fillAlpha = 0.5
        dataSet.fill = Fill(color: .green)
        dataSet.drawFilledEnabled = true
        
        callback(.value(dataSet))
    }
}
