//
//  ExpensesViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Charts
import XLPagerTabStrip

protocol ExpensesViewControllerOutput {
    func fetchLineData()
}

class ExpensesViewController: UIViewController {
    var refresh: UIRefreshControl!
    var output: ExpensesViewControllerOutput!
    var router: ExpensesRouter!
    
    @IBOutlet weak var chart: LineChartView!
    @IBOutlet weak var scrollView: UIScrollView!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        ExpensesConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        ExpensesConfigurator.sharedInstance.setup(theChart: chart)
        fetchLineData()
        setupRefresh(sel: #selector(reload))
    }
    
    func reload() {
        fetchLineData()
    }

    // MARK: - Event handling

    func fetchLineData() {
        startSpinning()
        output.fetchLineData()
    }

    // MARK: - Display logic

    func updateChart(viewModel: Expenses.Line.ViewModel) {
        chart.data = viewModel.data
        chart.animate(xAxisDuration: 1.0)
    }
}


extension ExpensesViewController: IndicatorInfoProvider {
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: " Expenses")
    }
}
