//
//  InboxInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum InboxFilterType {
    case all, processing, processed, approved, rejected
    
    var description: String {
        switch self {
        case .all: return "All"
        case .processing: return "Processing"
        case .processed: return "Processed"
        case .approved: return "Approved"
        case .rejected: return "Rejected"
        }
    }
}

protocol InboxInteractorOutput {
//      func presentSomething(response: Inbox.Something.Response)
}

class InboxInteractor {
    var output: InboxInteractorOutput!
    var worker: InboxWorker!
    
    var selectedInvoice: SyncConvertedInvoiceResponse!

}
