//
//  InboxInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol InboxInteractorOutput {
//      func presentSomething(response: Inbox.Something.Response)
}

class InboxInteractor {
    var output: InboxInteractorOutput!
    var worker: InboxWorker!

    // MARK: - Business logic
}
