//
//  InboxViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ActionSheetPicker_3_0
import XLPagerTabStrip

protocol InboxViewControllerOutput {
    var selectedInvoice: SyncConvertedInvoiceResponse! { get set }
}

class InboxViewController: UIViewController, Spinnable {
    fileprivate var dataSource: InboxDataSource!
    fileprivate var refresh: UIRefreshControl!
    
    var output: InboxViewControllerOutput!
    var router: InboxRouter!

    @IBOutlet weak var filter: UIButton!
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - IBActions
    
    @IBAction func pickFilter(_ sender: UIButton) {
        let picker = ActionSheetStringPicker(title: "Pick the filter",
                                             rows: InboxFilterType.allValues,
                                             initialSelection: 0,
                                             doneBlock: { [weak self] (_, _, value) in
                                                let title = value as! String
                                                DispatchQueue.main.async { self?.filter(with: title) }
                                            },
                                             cancel: nil,
                                             origin: self.view)
        
        picker?.show()
    }
    
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        InboxConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
    }

    // MARK: - Event handling
    
    func setupTableView() {
        tableView.register(InboxCell.nib, forCellReuseIdentifier: InboxCell.cellId)
        
        dataSource = InboxDataSource()
        dataSource.vcOutput = self
        tableView.dataSource = dataSource
        tableView.delegate = dataSource
        
        refresh = UIRefreshControl()
        refresh.addTarget(self, action: #selector(reload), for: .valueChanged)
        tableView.addSubview(refresh)
    }
    
    func reload() {
        resetFilter()
        dataSource.fetchInvoices()
    }
    
    func resetFilter() {
        filter.setTitle(InboxFilterType.all.description, for: .normal)
    }
    
    func filter(with query: String) {
        filter.setTitle(query, for: .normal)
        dataSource.filterModel(with: query)
    }
}

extension InboxViewController: InboxDataSourceVCOutput {
    func finishUpdatingTableView() {
        stopSpinning()
        refresh.endRefreshing()
        
        tableView.reloadData()
    }
    
    func startUpdatingTableView() {
        startSpinning()
    }
    
    func didSelect(the invoice: SyncConvertedInvoiceResponse) {
        output.selectedInvoice = invoice
        router.navigateToDetails()
    }
}

extension InboxViewController: IndicatorInfoProvider {
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: " Inbox  ")
    }
}
