//
//  InboxConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension InboxViewController: InboxPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension InboxInteractor: InboxViewControllerOutput {
}

extension InboxPresenter: InboxInteractorOutput {
}

class InboxConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = InboxConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: InboxViewController) {
        let router = InboxRouter()
        router.viewController = viewController

        let presenter = InboxPresenter()
        presenter.output = viewController

        let interactor = InboxInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
