//
//  InboxDataSourceWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct TempInboxInvoiceWorker {
    let name: String
    let paidOn: Date
    let status: String
    let currency: String
}

class InboxDataSourceWorker {
    // MARK: - Business Logic
    /// TODO: Replace later to RebotValueWrapper<SyncConvertedInvoiceResponse>
    func fetchInvoices(callback: (RebotValueWrapper<[TempInboxInvoiceWorker]>) -> ()) {
        let values = [
            TempInboxInvoiceWorker(name: "One", paidOn: Date(), status: "Extracted", currency: "$1.0"),
            TempInboxInvoiceWorker(name: "Two", paidOn: Date(), status: "Pending", currency: "$1.0"),
            TempInboxInvoiceWorker(name: "Very long name, because we want to test if the cell would be able to show such long name. We know it's barely possible but just in case", paidOn: Date(), status: "Ok", currency: "$1.0"),
            TempInboxInvoiceWorker(name: "Four", paidOn: Date(), status: "Ok", currency: "$10.0")
        ]
        
        callback(.value(values))
    }
}
