//
//  InboxDataSourceConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension InboxDataSource: InboxDataSourcePresenterOutput {
}

extension InboxDataSourceInteractor: InboxDataSourceOutput {
}

extension InboxDataSourcePresenter: InboxDataSourceInteractorOutput {
}

class InboxDataSourceConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = InboxDataSourceConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(dataSource: InboxDataSource) {
        let presenter = InboxDataSourcePresenter()
        presenter.output = dataSource

        let interactor = InboxDataSourceInteractor()
        interactor.output = presenter

        dataSource.output = interactor
    }
}
