//
//  InboxDataSourceInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol InboxDataSourceInteractorOutput {
    func presentInvoices(response: InboxDataSourceModel.Invoices.Response)
    func presentFilteredInvoices(response: InboxDataSourceModel.Filtered.Response)
}

class InboxDataSourceInteractor {
    var output: InboxDataSourceInteractorOutput!
    var worker: InboxDataSourceWorker!
    
    var invoices: [SyncConvertedInvoiceResponse]!
    var filteredInvoices: [SyncConvertedInvoiceResponse]!

    // MARK: - Business logic
    func fetchInvoices() {
        let entityId = AppSettings.shared.user.entityId
        worker = InboxDataSourceWorker(entityId: entityId)
        worker.fetchInvoices { [weak self] (wrappedArray) in
            self?.pass(data: wrappedArray)
        }
    }
    
    func filter(with query: String) {
        if query.lowercased() == "all" {
            passFiltered(invoices: invoices)
        }
        else {
            filteredInvoices = invoices.filter({ $0.type.lowercased() == query.lowercased() })
            passFiltered(invoices: filteredInvoices)
        }
    }
    
    func pass(data: RebotValueWrapper<[SyncConvertedInvoiceResponse]>) {
        storeInvoices(for: data)
        
        let response = InboxDataSourceModel.Invoices.Response(data: data)
        output.presentInvoices(response: response)
    }
    
    func passFiltered(invoices: [SyncConvertedInvoiceResponse]) {
        let response = InboxDataSourceModel.Filtered.Response(invoices: invoices)
        output.presentFilteredInvoices(response: response)
    }
    
    /// Save invoices in interactor for later usage
    ///
    /// - Parameter data: Wrapper of Sync Converted Invoice Response
    func storeInvoices(for data: RebotValueWrapper<[SyncConvertedInvoiceResponse]>) {
        switch data {
        case .value(let invoices):
            self.invoices = invoices
            self.filteredInvoices = invoices
        default: break
        }
    }
}
