//
//  InboxDataSourceInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol InboxDataSourceInteractorOutput {
      func presentInvoices(response: InboxDataSourceModel.Invoices.Response)
}

class InboxDataSourceInteractor {
    var output: InboxDataSourceInteractorOutput!
    var worker: InboxDataSourceWorker!

    // MARK: - Business logic
    func fetchInvoices() {
        worker = InboxDataSourceWorker()
        worker.fetchInvoices { [weak self] (wrappedArray) in
            self?.pass(data: wrappedArray)
        }
    }
    
    func pass(data: RebotValueWrapper<[TempInboxInvoiceWorker]>) {
        let response = InboxDataSourceModel.Invoices.Response(data: data)
        output.presentInvoices(response: response)
    }
}
