//
//  InboxDataSourceModels.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct InboxDataSourceModel {
    struct Cell {
        struct ViewModel {
            let name: String
            let paidOn: String
            let status: String
            let currency: String
        }
    }
    
    struct Invoices {
        struct Response {
            let data: RebotValueWrapper<[SyncConvertedInvoiceResponse]>
        }
        
        struct ViewModel {
            let cells: [Cell.ViewModel]
            
            var numberOfRows: Int {
                return cells.count
            }
            
            func cellModel(for indexPath: IndexPath) -> Cell.ViewModel {
                let row = indexPath.row
                return cells[row]
            }
        }
    }
    
    struct Filtered {
        struct Response {
            let invoices: [SyncConvertedInvoiceResponse]
        }
    }
}
