//
//  InboxDataSourceViewController.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol InboxDataSourceOutput {
    var invoices: [SyncConvertedInvoiceResponse]! { get set }
    var filteredInvoices: [SyncConvertedInvoiceResponse]! { get set }
    
    func fetchInvoices()
    func filter(with query: String)
}

protocol InboxDataSourceVCOutput {
    func startUpdatingTableView()
    func finishUpdatingTableView()
    func didSelect(the invoice: SyncConvertedInvoiceResponse)
}

class InboxDataSource: NSObject, UITableViewDelegate, UITableViewDataSource {
    var output: InboxDataSourceOutput!
    var vcOutput: InboxDataSourceVCOutput!
    var model: InboxDataSourceModel.Invoices.ViewModel!

    // MARK: - Object lifecycle
    override init() {
        super.init()
        InboxDataSourceConfigurator.sharedInstance.configure(dataSource: self)
        
        model = InboxDataSourceModel.Invoices.ViewModel(cells: [])
    }

    // MARK: - Event handling

    func fetchInvoices() {
        /// Notify that fetch request started
        vcOutput?.startUpdatingTableView()
        
        /// Fetch Invoices from internet
        output.fetchInvoices()
    }
    
    func filterModel(with query: String) {
        output.filter(with: query)
    }

    // MARK: - Display logic

    func update(model: InboxDataSourceModel.Invoices.ViewModel) {
        /// Replace current model with newer
        self.model = model
        
        /// Notify to reload the tableView
        vcOutput?.finishUpdatingTableView()
    }
    
    /// MARK: Table View methods
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return model.numberOfRows
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: InboxCell.cellId, for: indexPath) as? InboxCell else { fatalError("Can't load the cell!") }
        
        let cellModel = model.cellModel(for: indexPath)
        cell.setup(with: cellModel)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return 44.0
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableViewAutomaticDimension
    }
    
    func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return 0.01
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        
        let invoice = output.filteredInvoices[indexPath.row]
        vcOutput.didSelect(the: invoice)
    }
}
