//
//  InboxDataSourcePresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/7/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol InboxDataSourcePresenterOutput: class {
    func update(model: InboxDataSourceModel.Invoices.ViewModel)
}

class InboxDataSourcePresenter {
    weak var output: InboxDataSourcePresenterOutput!

    // MARK: - Presentation logic
    func presentInvoices(response: InboxDataSourceModel.Invoices.Response) {
        let data = response.data
        switch data {
        case .none(_):
            break /// TODO:
        case .value(let invoices):
            pass(theInvoices: invoices)
        }
    }
    
    func presentFilteredInvoices(response: InboxDataSourceModel.Filtered.Response) {
        pass(theInvoices: response.invoices)
    }
    
    func pass(theInvoices invoices: [SyncConvertedInvoiceResponse]) {
        var cellModels: [InboxDataSourceModel.Cell.ViewModel] = []
        
        for invoice in invoices {
            let paidOn = DateFormatters.mdytaFormatter.string(from: invoice.dueDate ?? Date())
            let currency = "£" + invoice.grossAmount
            let type = RebotInvoiceStatusMapper.toFrontEnd(from: invoice.type)
            let cellModel = InboxDataSourceModel.Cell.ViewModel(name: invoice.supplierName,
                                                                paidOn: paidOn,
                                                                status: type,
                                                                currency: currency)
            cellModels.append(cellModel)
        }
        
        let viewModel = InboxDataSourceModel.Invoices.ViewModel(cells: cellModels)
        output.update(model: viewModel)
    }
}
