//
//  PagerConfigurator.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PagerViewController: PagerPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension PagerInteractor: PagerViewControllerOutput {
}

extension PagerPresenter: PagerInteractorOutput {
}

class PagerConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = PagerConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: PagerViewController) {
        let router = PagerRouter()
        router.viewController = viewController

        let presenter = PagerPresenter()
        presenter.output = viewController

        let interactor = PagerInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
        
        viewController.settings.style.selectedBarHeight = 4
        viewController.settings.style.selectedBarBackgroundColor = RebotColor.Pager.separator
        viewController.settings.style.buttonBarItemBackgroundColor = .clear
        viewController.settings.style.buttonBarItemsShouldFillAvailableWidth = true
        viewController.settings.style.buttonBarItemLeftRightMargin = 15.0
    }
}
