//
//  PagerInteractor.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PagerInteractorOutput {
    
}

class PagerInteractor {
    var takenPhoto: UIImage!
    var output: PagerInteractorOutput!
    var worker = PagerWorker()
    
    var viewControllers: [UIViewController] {
        guard let dashboard = worker.storyboard(name: "Dashboard"),
            let expenses = worker.storyboard(name: "Expenses"),
            let inbox = worker.storyboard(name: "Inbox")
            else { return [] }
        
        return [
            dashboard,
            expenses,
            inbox
        ]
    }
}
