//
//  PagerPresenter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PagerPresenterInput {
    func presentSomething(response: Pager.Something.Response)
}

protocol PagerPresenterOutput: class {
    func displaySomething(viewModel: Pager.Something.ViewModel)
}

class PagerPresenter: PagerPresenterInput {
    weak var output: PagerPresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: Pager.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = Pager.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
