//
//  PagerRouter.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PagerRouterInput {
    func navigateToCamera()
}

class PagerRouter: PagerRouterInput {
    weak var viewController: PagerViewController!

    // MARK: - Navigation
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == "ShowVerifyFromPager" {
            passDataToCameraVerifyScene(segue: segue)
        }
    }
    
    func navigateToCamera() {
        viewController.performSegue(withIdentifier: "ShowCameraView", sender: nil)
    }
    
    func navigateToVerify() {
        viewController.performSegue(withIdentifier: "ShowVerifyFromPager", sender: nil)
    }

    // MARK: - Communication
    func passDataToCameraVerifyScene(segue: UIStoryboardSegue) {
        let photoVerifyViewController = segue.destination as! PhotoVerifyViewController
        photoVerifyViewController.takenPhoto = viewController.output.takenPhoto
    }
}
