//
//  PagerWorker.swift
//  ReceiptBot
//
//  Created by Haik Ampardjian on 4/5/17.
//  Copyright (c) 2017 receiptbot. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class PagerWorker {
    func storyboard(name: String) -> UIViewController? {
        return UIStoryboard(name: name, bundle: Bundle.main).instantiateInitialViewController()
    }
}
